### ISSUE TITLE
Dumping images from the Current Album only causes a new blank window to open (named about:blank)

### ISSUE THREAD

**Issue by LukasExemplar** [arioux/DumpItBluePlus#2]
When trying to dump images, the program merely opens up a brand new but blank window, with the name `about:blank`, and it doesn't seem to do the actual dumping.

Is there anything I need to do first for this not to happen and for the dumping process to do what it should actually be doing? I assume that opening up a new blank window is not something you designed for it to do, but I just wanted to make sure. For instance, I thought it might be using said window in-between the time when the dumping starts and end somehow but wasn't sure.

**Comment by arioux** [comment]
It will be fixed in the next release coming soon. Currently on pending review status on Chrome Web store. Thanks for your comment!
